In [1]:
import mod1_intel

In [2]:
a = mod1_intel.to_excel()

In [3]:
a.get_program_trend_date(choice=2)

444
444

Empty DataFrame
Columns: [차익, 비차익, 전체]
Index: []

In [4]:
a.get_investor_trend_date(choice=2)

431
431

Empty DataFrame
Columns: [개인, 외국인, 기관]
Index: []

In [5]:
a.get_kpi200_date(choice=2)

766
766

Empty DataFrame
Columns: [KPI200, 거래량]
Index: []

In [6]:
a.get_money_trend_date(choice=2)

275
275

Empty DataFrame
Columns: [고객예탁금, 신용잔고, 주식형펀드, 혼합형펀드, 채권형펀드]
Index: []

In [7]:
#a.future(choice=2)

In [8]:
a.sector()

HTTPError: HTTP Error 308: Permanent Redirect

In [ ]:
#a.kospi_kosdaq()

In [9]:
b = mod1_intel.to_sql()

In [ ]:
b.excel_to_sql(choice=2)

kpi200
Empty DataFrame
Columns: [Date, KPI200, 거래량]
Index: []
investortrend
Empty DataFrame
Columns: [Date, 개인, 외국인, 기관]
Index: []
moneytrend
Empty DataFrame
Columns: [Date, 고객예탁금, 신용잔고, 주식형펀드, 혼합형펀드, 채권형펀드]
Index: []
programtrend
Empty DataFrame
Columns: [Date, 차익, 비차익, 전체]
Index: []
kospi_sector
          date sectorName  changeRate    first       second
0   2024-05-16         보험    5.077477     삼성화재        삼성화재우
1   2024-05-16        금융업    1.750417     삼성화재        삼성화재우
2   2024-05-16         기계    1.486922  다이나믹디자인         두산밥캣
3   2024-05-16    코스피 중형주    1.305298   이수페타시스  LS ELECTRIC
4   2024-05-16      비금속광물    1.223299    한일시멘트       아세아시멘트
5   2024-05-16      철강및금속    1.039082       서원         고려아연
6   2024-05-16        의약품    0.924821     유유제약         유한양행
7   2024-05-16      전기,전자    0.872077   이수페타시스  LS ELECTRIC
8   2024-05-16         증권    0.856981   한화투자증권      한화투자증권우
9   2024-05-16        코스피    0.829933    한국화장품      한국화장품제조
10  2024-05-16        제조업    0.792530  한국화장품제조       이수페타시스
11  2024-05-16    코스피 대형주    0.788101     삼성화재       DB손해보험
12  2024-05-16        유통업    0.726752    한국화장품      현대코퍼레이션
13  2024-05-16    코스피 소형주    0.668871    한국화장품      한국화장품제조
14  2024-05-16       의료정밀    0.668562      디아이          케이씨
15  2024-05-16         화학    0.592751  한국화장품제조        그린케미칼
16  2024-05-16        건설업    0.553710   SK이터닉스         화성산업
17  2024-05-16      전기가스업    0.528190   SGC에너지       한국가스공사
18  2024-05-16       서비스업    0.426259     비상교육          코웨이
19  2024-05-16      섬유,의복    0.425549       TP         한세실업
20  2024-05-16        통신업    0.396070       KT        현대퓨처넷
21  2024-05-16       운수장비    0.299095      체시스         태양금속
22  2024-05-16       음식료품    0.133307    CJ씨푸드        사조씨푸드
23  2024-05-16      종이,목재    0.077924     태림포장       깨끗한나라우
24  2024-05-16       운수창고   -2.899165   현대글로비스         천일고속
kosdaq_sector
          date    sectorName  changeRate       first     second
0   2024-05-16        일반전기전자    2.126462      제일일렉트릭     세경하이테크
1   2024-05-16            금융    2.122475     인카금융서비스   HB인베스트먼트
2   2024-05-16         기타 제조    2.090233       엑스플러스       휴엠앤씨
3   2024-05-16         기타서비스    1.688156      지오릿에너지      랩지노믹스
4   2024-05-16           반도체    1.499453          미코       HPSP
5   2024-05-16       의료·정밀기기    1.361440       이오플로우    제이시스메디칼
6   2024-05-16           비금속    1.261928       원익QnC         SG
7   2024-05-16           대형주    1.111969        HPSP   피에스케이홀딩스
8   2024-05-16        IT H/W    1.066341        빛과전자     바이오스마트
9   2024-05-16           중형주    1.018365       켐트로닉스         미코
10  2024-05-16            유통    0.955909        실리콘투    오하임앤컴퍼니
11  2024-05-16           코스닥    0.953430  스카이문스테크놀로지       윙입푸드
12  2024-05-16            제조    0.921336       이오플로우      켐트로닉스
13  2024-05-16         기계·장비    0.839788    상상인인더스트리    HB테크놀러지
14  2024-05-16            제약    0.723763     메타바이오메드        티앤엘
15  2024-05-16            IT    0.690751  스카이문스테크놀로지       빛과전자
16  2024-05-16           소형주    0.660402  스카이문스테크놀로지      이오플로우
17  2024-05-16            금속    0.651705    해성에어로보틱스      케이피에프
18  2024-05-16         오락·문화    0.592992       에이스토리       래몽래인
19  2024-05-16            건설    0.590145       세보엠이씨     신원종합개발
20  2024-05-16         통신서비스    0.500697     나이스정보통신       케이엘넷
21  2024-05-16           인터넷    0.411101  브랜드엑스코퍼레이션        가비아
22  2024-05-16       출판·매체복제    0.381348         FSN  아티스트유나이티드
23  2024-05-16          정보기기    0.357462      바이오스마트     데이타솔루션
24  2024-05-16          통신장비    0.329025        빛과전자         CS
25  2024-05-16            화학    0.279806       켐트로닉스     엔터파트너즈
26  2024-05-16         종이·목재    0.191460       스피어파워    리더스코스메틱
27  2024-05-16          IT부품    0.086049        성호전자       디아이티
28  2024-05-16        디지털컨텐츠    0.039004  스카이문스테크놀로지     디앤씨미디어
29  2024-05-16  IT S/W & SVC   -0.046646  스카이문스테크놀로지      지어소프트
30  2024-05-16         소프트웨어   -0.087439       지어소프트     토마토시스템
31  2024-05-16       운송장비·부품   -0.139195          세동       일지테크
32  2024-05-16         섬유·의류   -0.151630        씨싸이트      패션플랫폼
33  2024-05-16       통신방송서비스   -0.349270     나이스정보통신       케이엘넷
34  2024-05-16            운송   -0.445687        SG&G         삼일
35  2024-05-16         방송서비스   -0.729953      SM C&C     한국경제TV
36  2024-05-16        컴퓨터서비스   -0.806731      아이크래프트     폴라리스AI
37  2024-05-16        음식료·담배   -0.906630         뉴트리        푸드웰
0    2024-08-07
Name: Date, dtype: object

 market start_date:2024-08-08
000020 동화약품
000040 KR모터스
000050 경방
000070 삼양홀딩스
000075 삼양홀딩스우
000080 하이트진로
000087 하이트진로2우B
000100 유한양행
000105 유한양행우
000120 CJ대한통운
000140 하이트진로홀딩스
000145 하이트진로홀딩스우
000150 두산
000155 두산우
000157 두산2우B
000180 성창기업지주
000210 DL
000215 DL우
000220 유유제약
000225 유유제약1우
000227 유유제약2우B
000230 일동홀딩스
000240 한국앤컴퍼니
000250 삼천당제약
000270 기아
000300 대유플러스
000320 노루홀딩스
000325 노루홀딩스우
000370 한화손해보험
000390 삼화페인트
000400 롯데손해보험
000430 대원강업
000440 중앙에너비스
000480 CR홀딩스
000490 대동
000500 가온전선
000520 삼일제약
000540 흥국화재
000545 흥국화재우
000590 CS홀딩스
000640 동아쏘시오홀딩스
000650 천일고속
000660 SK하이닉스
000670 영풍
000680 LS네트웍스
000700 유수홀딩스
000720 현대건설
000725 현대건설우
000760 이화산업
000810 삼성화재
000815 삼성화재우
000850 화천기공
000860 강남제비스코
000880 한화
000885 한화우
000890 보해양조
000910 유니온
000950 전방
000970 한국주철관
000990 DB하이텍
001000 신라섬유
001020 페이퍼코리아
001040 CJ
001045 CJ우
001060 JW중외제약
001065 JW중외제약우
001067 JW중외제약2우B
001070 대한방직
001080 만호제강
001120 LX인터내셔널
001130 대한제분
001140 국보
001200 유진투자증권
001210 금호전기
001230 동국홀딩스
001250 GS글로벌
001260 남광토건
001270 부국증권
001275 부국증권우
001290 상상인증권
001340 백광산업
001360 삼성제약
001380 SG글로벌
001390 KG케미칼
001420 태원물산
001430 세아베스틸지주
001440 대한전선
001450 현대해상
001460 BYC
001465 BYC우
001470 삼부토건
001500 현대차증권
001510 SK증권
001515 SK증권우
001520 동양
001525 동양우
001527 동양2우B
001530 DI동일
001540 안국약품
001550 조비
001560 제일연마
001570 금양
001620 케이비아이동국실업
001630 종근당홀딩스
001680 대상
001685 대상우
001720 신영증권
001740 SK네트웍스
001750 한양증권
001755 한양증권우
001770 SHD
001780 알루코
001790 대한제당
001795 대한제당우
001800 오리온홀딩스
001810 무림SP
001820 삼화콘덴서
001840 이화공영
001940 KISCO홀딩스
002020 코오롱
002025 코오롱우
002030 아세아
002070 비비안
002100 경농
002140 고려산업
002150 도화엔지니어링
002170 삼양통상
002200 한국수출포장
002210 동성제약
002220 한일철강
002230 피에스텍
002240 고려제강
002290 삼일기업공사
002310 아세아제지
002320 한진
002350 넥센타이어
002355 넥센타이어1우B
002360 SH에너지화학
002380 KCC
002390 한독
002410 범양건영
002420 세기상사
002450 삼익악기
002460 화성산업
002600 조흥
002620 제일파마홀딩스
002630 오리엔트바이오
002680 한탑
002690 동일제강
002700 신일전자
002710 TCC스틸
002720 국제약품
002760 보락
002780 진흥기업
002785 진흥기업우B
002787 진흥기업2우B
002790 아모레G
002795 아모레G우
002800 신신제약
002810 삼영무역
002820 SUN&L
002840 미원상사
002870 신풍
002880 대유에이텍
002900 TYM
002920 유성기업
002960 한국쉘석유
002990 금호건설
002995 금호건설우
003000 부광약품
003010 혜인
003030 세아제강지주
003060 에이프로젠바이오로직스
003070 코오롱글로벌
003075 코오롱글로벌우
003080 성보화학
003090 대웅
003100 선광
003120 일성신약
003160 디아이
003200 일신방직
003220 대원제약
003230 삼양식품
003240 태광산업
003280 흥아해운
003300 한일홀딩스
003310 대주산업
003350 한국화장품제조
003380 하림지주
003410 쌍용C&E
003460 유화증권
003465 유화증권우
003470 유안타증권
003475 유안타증권우
003480 한진중공업홀딩스
003490 대한항공
003495 대한항공우
003520 영진약품
003530 한화투자증권
003535 한화투자증권우
003540 대신증권
003545 대신증권우
003547 대신증권2우B
003550 LG
003555 LG우
003560 IHQ
003570 SNT다이내믹스
003580 HLB글로벌
003610 방림
003620 KG모빌리티
003650 미창석유
003670 포스코퓨처엠
003680 한성기업
003690 코리안리
003720 삼영
003780 진양산업
003800 에이스침대
003830 대한화섬
003850 보령
003920 남양유업
003925 남양유업우
003960 사조대림
004000 롯데정밀화학
004020 현대제철
004060 SG세계물산
004080 신흥
004090 한국석유
004100 태양금속
004105 태양금속우
004140 동방
004150 한솔홀딩스
004170 신세계
004250 NPC
004255 NPC우
004270 남성
004310 현대약품
004360 세방
004365 세방우
004370 농심
004380 삼익THK
004410 서울식품
004415 서울식품우
004430 송원산업
004440 삼일씨엔에스
004450 삼화왕관
004490 세방전지
004540 깨끗한나라
004545 깨끗한나라우
004560 현대비앤지스틸
004590 한국가구
004650 창해에탄올
004690 삼천리
004700 조광피혁
004710 한솔테크닉스
004720 팜젠사이언스
004770 써니전자
004780 대륙제관
004800 효성
004830 덕성
004835 덕성우
004840 DRB동일
004870 티웨이홀딩스
004890 동일산업
004910 조광페인트
004920 씨아이테크
004960 한신공영
004970 신라교역
004980 성신양회
004985 성신양회우
004990 롯데지주
005010 휴스틸
005030 부산주공
005070 코스모신소재
005090 SGC에너지
005110 한창
005160 동국산업
005180 빙그레
005250 녹십자홀딩스
005257 녹십자홀딩스2우
005290 동진쎄미켐
005300 롯데칠성
005305 롯데칠성우
005320 국동
005360 모나미
005380 현대차
005385 현대차우
005387 현대차2우B
005389 현대차3우B
005390 신성통상
005420 코스모화학
005430 한국공항
005440 현대지에프홀딩스
005490 POSCO홀딩스
005500 삼진제약
005610 SPC삼립
005670 푸드웰
005680 삼영전자
005690 파미셀
005710 대원산업
005720 넥센
005725 넥센우
005740 크라운해태홀딩스

005745 크라운해태홀딩스우
005750 대림B&Co
005800 신영와코루
005810 풍산홀딩스
005820 원림
005830 DB손해보험
005850 에스엘
005860 한일사료
005870 휴니드
005880 대한해운
005930 삼성전자
005935 삼성전자우
005940 NH투자증권
005945 NH투자증권우
005950 이수화학
005960 동부건설
005965 동부건설우
005990 매일홀딩스
006040 동원산업
006050 국영지앤엠
006060 화승인더
006090 사조오양
006110 삼아알미늄
006120 SK디스커버리
006125 SK디스커버리우
006140 피제이전자
006200 한국전자홀딩스
006220 제주은행
006260 LS
006280 녹십자
006340 대원전선
006345 대원전선우
006360 GS건설
006370 대구백화점
006380 카프로
006390 한일현대시멘트
006400 삼성SDI
006405 삼성SDI우
006490 인스코비
006570 대림통상
006580 대양제지
006620 동구바이오제약
006650 대한유화
006660 삼성공조
006730 서부T&D
006740 영풍제지
006800 미래에셋증권
006805 미래에셋증권우
006840 AK홀딩스
006880 신송홀딩스
006890 태경케미컬
006910 보성파워텍
006920 모헨즈
006980 우성
007070 GS리테일
007110 일신석재
007120 미래아이앤지
007160 사조산업
007210 벽산
007280 한국특강
007310 오뚜기
007330 푸른저축은행
007340 DN오토모티브
007370 진양제약
007390 네이처셀
007460 에이프로젠
007530 와이엠
007540 샘표
007570 일양약품
007575 일양약품우
007590 동방아그로
007610 선도전기
007660 이수페타시스
007680 대원
007690 국도화학
007700 F&F홀딩스
007720 대명소노시즌
007770 한일화학
007810 코리아써키트
007815 코리아써우
007820 에스엠코어
007860 서연
007980 태평양물산
008040 사조동아원
008060 대덕
008110 대동전자
008250 이건산업
008260 NI스틸
008290 원풍물산
008350 남선알미늄
008355 남선알미우
008370 원풍
008420 문배철강
008470 부스타
008490 서흥
008500 일정실업
008600 윌비스
008700 아남전자
008730 율촌화학
008770 호텔신라
008775 호텔신라우
008830 대동기어
008870 금비
008930 한미사이언스
008970 동양철관
009070 KCTC
009140 경인전자
009150 삼성전기
009155 삼성전기우
009160 SIMPAC
009180 한솔로지스틱스
009190 대양금속
009200 무림페이퍼
009240 한샘
009270 신원
009290 광동제약
009300 삼아제약
009310 참엔지니어링
009320 대우부품

In [ ]:
from mod1_intel import *
 
kospi_kosdaq(market='1001')
kospi_kosdaq(market='2001')

In [ ]:
import kkkk

In [5]:
import requests

In [6]:
from mod1 import *

KRX 로그인 실패: KRX_ID 또는 KRX_PW 환경 변수가 설정되지 않았습니다.

In [ ]:
def kospi_kosdaq(lastday='20251231', market='1001'):
    if market == '1001':
        df = get_index_ohlcv_by_date(kospi_next_day_no_hypyen, lastday, market)
        df.index.names = ['Date']
        df = df.iloc[:,[0,1,2,3,4]]
        df.columns  = ['Open','High','Low','Close','Volume']
        df['Market']='kospi'
        df.to_sql(name='kospi', con=engine, if_exists='append')
    elif market == '2001':
        df = get_index_ohlcv_by_date(kospi_next_day_no_hypyen, lastday, market)
        df.index.names = ['Date']
        df = df.iloc[:,[0,1,2,3,4]]
        df.columns  = ['Open','High','Low','Close','Volume']        
        df['Market']='kosdaq'
        df.to_sql(name='kosdaq', con=engine, if_exists='append')
kospi_kosdaq( market='1001')

In [ ]:
df = get_index_ohlcv_by_date(kospi_next_day_no_hypyen,'20251231'. '1001')
df

In [ ]:
get_index_ohlcv_by_date('20221201','20251231', '1001')

###